# Shadowrocket: 2024-02-19 19:05:00
[General]
bypass-system = true
ipv6 = false
prefer-ipv6 = false
private-ip-answer = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captive.apple.com, *.ccb.com, *.abchina.com.cn, *.psbc.com, www.baidu.com, wxh.wo.cn
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32, 239.255.255.250/32
dns-server = https://dns.alidns.com/dns-query, https://doh.pub/dns-query, 223.5.5.5, 119.29.29.29
fallback-dns-server = system
dns-direct-system = false
dns-direct-fallback-proxy = false
hijack-dns = 8.8.8.8:53,8.8.4.4:53
icmp-auto-reply = true
always-reject-url-rewrite = false
udp-policy-not-supported-behaviour = REJECT
update-url = https://raw.githubusercontent.com/iArr0w/Shadow/main/MyShadowMini.conf

[Rule]
AND,((PROTOCOL,UDP),(DST-PORT,443)),REJECT-NO-DROP
RULE-SET,https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Filter/Extra/Apple/BlockiOSUpdate.list,REJECT
DOMAIN-SET,https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge2.txt,REJECT
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Lan/Lan_Resolve.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/VirgilClyne/GetSomeFries/main/ruleset/ASN.China.list,DIRECT
FINAL,PROXY

[Host]
localhost = 127.0.0.1

[URL Rewrite]
^https?:\/\/(www.)?(g|google)\.cn https://www.google.com 302

[MITM]
hostname = www.google.cn
